---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: GoogleCloudPlatform/release-please-action@v2
      with:
        release-type: simple
